name: places
version: "0.0.1-dev.0"
description: a Flutter template project for development.
publish_to: none

dependencies:
  bloc: ^8.0.3
  bloc_concurrency: ^0.2.0 
  cached_network_image: ^3.2.1
  connectivity_plus: ^2.3.0
  dio: ^4.0.4
  elementary: ^1.0.0
  firebase_crashlytics: ^2.3.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^1.0.3
  freezed: ^2.0.3+1 
  freezed_annotation: ^2.0.3
  geolocator: ^8.2.1
  infinite_scroll_pagination: ^3.1.0
  intl: ^0.17.0
  json_annotation: ^4.5.0
  json_serializable: ^6.2.0
  logger: ^1.1.0
  mocktail: ^0.3.0
  provider: ^6.0.2
  retrofit: ^3.0.1+1
  shared_preferences: ^2.0.15
  surf_lint_rules: ^1.5.0
  surf_logger: ^1.0.2
  surf_util: ^1.0.3

  

dev_dependencies:
  build_runner: ^2.1.11
  dart_code_metrics: ^4.7.0
  elementary_test: ^1.0.1
  flutter_test:
    sdk: flutter
  retrofit_generator: ^4.0.1
  
  
  
  

environment:
  sdk: ">=2.17.0-0 <3.0.0"

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/icons/
    - assets/icons/catalog/
    - assets/icons/onboarding/
    - assets/icons/empty_pages/
    - assets/icons/menu/
    - assets/icons/other/
    - assets/images/
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Thin.ttf
          weight: 100
        - asset: assets/fonts/Roboto-ThinItalic.ttf
          weight: 100
          style: italic
        - asset: assets/fonts/Roboto-Light.ttf
          weight: 300
        - asset: assets/fonts/Roboto-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/Roboto-Regular.ttf
          weight: 400
        - asset: assets/fonts/Roboto-Italic.ttf
          weight: 400
          style: italic 
        - asset: assets/fonts/Roboto-Medium.ttf
          weight: 500
        - asset: assets/fonts/Roboto-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700
        - asset: assets/fonts/Roboto-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/Roboto-Black.ttf
          weight: 900
        - asset: assets/fonts/Roboto-BlackItalic.ttf
          weight: 900
          style: italic
